export interface Details {
    ticker: string,
    name: string,
    price: number,
    change: number,
    changePercent: number,
    description: string,
    high: number,
    low: number,
    open: number,
    prevClose: number,
    volume: number,
    startDate: string,
    timestamp: string,
    mid: number,
    askPrice: number,
    askSize: number,
    bidPrice: number,
    bidSize: number,
    last: number,
}